### ISSUE TITLE
Roku Source Code

### ISSUE THREAD

**Issue by llamasoft** [prototux/tcl-tv-re#1]
This isn't really an issue, I just didn't have a better way to contact you.  
I just wanted to let you know that your project inspired me to do a bit of digging and I stumbled across Roku's [open source software](https://www.roku.com/separatelylicensedcode) listing.  The 100% proprietary code like sitatvservice isn't in there, but their modifications to open source projects are.  Of special note are the [u-boot projects](https://roku.app.box.com/v/RokuOpenSourceSoftware/folder/41652015247).  By diffing them with the [official release](https://github.com/u-boot/u-boot/releases/tag/v2014.04) versions of the same tag, you can discern a good bit.  The latest projects seem to be lacking u-boot, but this seemed like a good way to start discerning what goes on during the boot process.

**Comment by prototux** [comment]
Hello,

Well, my email in my profile page is working ;)

I've looked a bit into roku's open source archives (thanks for the link!), and there's only roku's own products OSS code apparently, which is kinda expected. I didn't found references to the SoC used in TCL's TVs or some other software that they use (including their own sitatvservice, which is specific to TCL as far as i know).

The boot process isn't really that mystical in TCL TVs, the two unknown bits here are the "secos" used for netflix's DRM and the SoC specific parts, the rest seems to be somewhat a standard uboot. I have no plan to dig into the secos as it's the netflix's DRM (and i have no interest to reverse engineer that, especially given the lawsuit that could come quickly), and the SoC specific part will not be open source i think, it's already a pretty unknown SoC made by a pretty unknown vendor, so i don't expect any new detail to come out about this specific model, sadly.

It's the same for the kernel actually, and the rest is mostly libfpp.so and sitatvservice. everything else is "standard" (or useless) software, such as the standard netflix app for TVs, the standard hbbtv browser, etc.

If you want to make your own opensource TCL tv, that's basically it: uboot, linux kernel, sitatvservice with libfpp (and companion libs) and a bunch of random other app with directfb rendering on top of that.

The current status right now is that i have a minimalistic service running on top of libfpp (effectively replacing sitatvservice, but with less features) at https://github.com/prototux/FvgnTvService and there's bit of "leaked" (well, commited on github by mistake) bits of sitatvservice such as https://github.com/21sec/binder/blob/master/linein/fpi_linein.c . The libfpp.so isn't reverse engineered yet, because my primary goal was to have my own sitatvservice replacement working, but it could be done. It seems that libfpp uses mostly i2c and UART to send commands to the scaler chip and other parts of the TV, so it's pretty much down to that, understanding what i2c/uart/spi command to send and where.
